### ISSUE TITLE
[Important] Doesn't compile on OS X 10.6

### ISSUE THREAD

**Issue by coolaj86** [smaniam/mtags#2]
```
make libs

checking build system type... i386-apple-darwin10.4.0
checking host system type... i386-apple-darwin10.4.0
checking target system type... i386-apple-darwin10.4.0

-- snip --

cd lib/AtomicParsley; ./build;
Compiling AP_commons.cpp ...
Compiling AtomicParsley_genres.cpp ...
Compiling AP_iconv.cpp ...
Compiling AP_NSFile_utils.mm ...
AP_NSFile_utils.mm: In function ‘uint32_t APar_4CC_CreatorCode(const char*, uint32_t)’:
Compiling AP_NSImage.mm ...
AP_NSImage.mm: In function ‘bool ResizeGivenImage(const char*, PicPrefs, char*)’:
AP_NSImage.mm:204: error: ‘_NSBitmapImageFileType’ was not declared in this scope
AP_NSImage.mm:204: error: expected `;' before ‘filetype’
AP_NSImage.mm:208: error: ‘filetype’ was not declared in this scope
AP_NSImage.mm:212: error: ‘filetype’ was not declared in this scope
AP_NSImage.mm:216: error: ‘filetype’ was not declared in this scope
Compiling AtomicParsley.cpp ...
In file included from AtomicParsley.cpp:40:
AtomicParsley.cpp: In function ‘void APar_ExtractAAC_Artwork(short int, char*, short int)’:
AtomicParsley.cpp: In function ‘void APar_PrintDataAtoms(const char*, char*, uint8_t, uint8_t)’:
AtomicParsley.cpp: In function ‘void APar_ForcePadding(uint32_t)’:
AtomicParsley.cpp: In function ‘void APar_ConsilidatePadding(uint32_t)’:
AtomicParsley.cpp: In function ‘void APar_ForcePadding_sans_udta()’:
AtomicParsley.cpp: In function ‘void APar_DetermineDynamicUpdate(bool)’:
AtomicParsley.cpp: In function ‘void APar_MetadataFileDump(const char*)’:
Compiling AP_AtomExtracts.cpp ...
AP_AtomExtracts.cpp: In function ‘void APar_ShowObjectProfileInfo(uint8_t, TrackInfo*)’:
AP_AtomExtracts.cpp: In function ‘void APar_ExtractTrackDetails(char*, FILE*, Trackage*, TrackInfo*)’:
Compiling APar_sha1.cpp ...
Compiling APar_uuid.cpp ...
APar_uuid.cpp: In function ‘void APar_generate_uuid_from_atomname(char*, char*)’:
APar_uuid.cpp: In function ‘void APar_generate_test_uuid()’:
Compiling main.cpp ...
main.cpp: In function ‘int main(int, char**)’:
Linking AtomicParsley...
i686-apple-darwin10-g++-4.2.1: obj_files/AP_NSImage.o: No such file or directory
strip: can't open file: AtomicParsley (No such file or directory)
make: *** [AtomicParsley] Error 1
```

**Comment by smaniam** [comment]
Issues with AtomicParsley 0.9. It will be fixed as part of Bitbucket upgrade.

**Comment by coolaj86** [comment]
I've added the new version of AtomicParsley to the build-deps.sh.

The old could be commented out and the new uncommented pretty easily.

There appear to be only a few problems such as functions that have changed names between versions.

**Comment by coolaj86** [comment]
The libraries are properly specified in atomicparsley. Now compiles.
